import AuthProvider from "@/components/AuthProvider";
import "./globals.css";

import { ReactNode } from "react";
import SessionAuth from "@/components/SessionAuth";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Ecommerce Admin",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className="w-[1200px] h-[740px] bg-[#131921] mx-auto my-10 flex text-white">
        <AuthProvider>
          <SessionAuth>
            <Navbar />
            <div className="w-[1000px] bg-[#364759] relative rounded-r-lg p-5">
              {children}
            </div>
          </SessionAuth>
        </AuthProvider>
      </body>
    </html>
  );
}
